apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1 # 5 # 3 #1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        # - image: gcr.io/google-samples/gb-frontend:v5
        - image: php:8-apache # us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5 # ghcr.io/bitnami/guestbook-frontend #bitnami/guestbook-frontend
          name: guestbook-ui
          ports:
            - containerPort: 80
